apiVersion: v1
kind: Service
metadata:
  name: shopping-cart
  labels:
    app: shopping-cart
spec:
  ports:
  - port: 80
    targetPort: 8070
    protocol: TCP
    nodePort: 30007
  selector:
    app: shopping-cart
  type: NodePort