name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  codacy-analysis-cli:
  
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
      

  Build-and-push:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean package
    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: check files
      run: |
          pwd
          ls target/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/shopping-cart:${{github.run_number}}


  Image-Scan:
    name: Trivy Image Scan
    runs-on: ubuntu-20.04
    needs: Build-and-push

    steps:
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@0.20.0
          with:
            image-ref: 'docker.io/${{ secrets.DOCKERHUB_USERNAME }}/shopping-cart:${{github.run_number}}'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
     


  Update-newtag-in-deployment:
    runs-on: ubuntu-latest
    needs: Build-and-push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in deployment file
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_number}}"/' helm/shopping-cart/values.yaml
        cat helm/go-web-app-chart/values.yaml | grep tag

    - name: Commit and push changes
      run: |
        git config --global user.email "shivaponnaganti5@gmail.com"
        git config --global user.name "shiva-ponnaganti"
        git add helm/shopping-cart/values.yaml
        git commit -m "Update tag in deployment"
        git push

  
